#import uni list and uni data -- wrangle uni names to sort/join lists
# SETUP ------
library(tidyverse)
library(readxl)
library(fuzzyjoin)

source("code/get_wrangle_uni_functions.R")

#import carnegie data----
source("code/clean_carn_data.R")

#import non-carnegie inst names----
non_carn_inst_data <- read_csv("data/non-carnegie_unis.csv")%>% 
  select(Institution) %>% 
  mutate(Institution = str_to_title(Institution),
         Institution = str_remove_all(Institution, ",|'"),
         Institution = str_replace(Institution, "U\\.? |U$|Univ\\.? |Univ$|Uni\\w*\\b|Uni |Unviersity", "University "),
         Institution = str_replace(Institution, "Saint |^St ", "St "),
         Institution = str_replace_all(Institution, pattern = "&", replacement = "And"),
         Institution = str_replace_all(Institution, pattern = " At | In |,, |/|-|–", replacement = " "),
         Institution = str_squish(Institution))

#create master list of inst names
inst_name_list <- rename(non_carn_inst_data, "NAME" = "Institution") %>% 
  rbind(., carnegie_inst_names)

#import survey uni list (generated by "get_full_inst_data.R")----
full_inst_data <- read_csv("output/full_inst_list_2019-2022_2023-03-03.csv")

unique_inst_list <- full_inst_data %>% 
  mutate(id = paste0(id, "_", survey_year)) %>% 
  select(id, inst_type, inst_name) %>% distinct()

#list of non-Carnegie institutions
#non_carn_inst <- c("Inc|Associat|Society|Hospital| Lab|Foundation")

#non-inst entries to drop----
drop_list <- c("NA|N A|Na|— Make A Selection —|None|
               Post Doc|Postdoc|Lab Moved)|
               Unofficial Offer|N/A|General Search)|
               Verbal|Completed Phd But Not Employed")

#clean inst names for all survey responses----
clean_surv_inst <- unique_inst_list %>% 
  filter(str_detect(inst_name, drop_inst) == FALSE) %>% 
  filter(inst_name %not_in% drop_list) %>% 
  filter(!is.null(inst_name)) %>% 
  filter(!is.na(inst_name)) %>% 
  mutate(inst_name = str_replace(inst_name, "U\\.? |U$|Univ\\.? |Univ$|Uni\\w*\\b|Uni |Unviersity", "University "),
         inst_name = str_replace(inst_name, "Saint |^St ", "St "),
         inst_name = str_replace_all(inst_name, pattern = "&", replacement = "And"),
         inst_name = str_replace_all(inst_name, "Aandm|AAndM", "A And M"),
         inst_name = str_replace_all(inst_name, "Aandt|AAndT", "A And T"),
         inst_name = str_remove_all(inst_name, " Som$| Mentor Cluster Search| Neurotheme Search|In Seattle|,|The |\\.|Campus|Tuscaloosa|\\(|\\(.*Post.*|\\)| (?=,)|@|'|Search Results Web Results |Israel"),
         inst_name = str_replace_all(inst_name, pattern = " At | In |,, |/|-|–", replacement = " "),
         inst_name = str_replace(inst_name, " Or ", " Of "))

clean_surv_inst <- clean_surv_inst %>% 
  mutate(inst_name = map(inst_name, replace_uny),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_inst_abbrv),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_inst_name),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_campus),
         inst_name = unlist(inst_name),
         inst_name = str_to_title(inst_name),
         inst_name = str_squish(inst_name)
         ) %>% 
  filter(str_detect(inst_name, "Postdoc|Post Doc") == FALSE)

#inst name join----
inst_join <- inst_name_list %>% 
  mutate(NAME = str_remove_all(NAME, ",")) %>% #ensure no commas
  left_join(clean_surv_inst, ., 
            by = c("inst_name" = "NAME"), keep = TRUE) %>%
  select(-id, -inst_type) %>% #option to keep or drop identifying data
  distinct()

#identify respondent inst that did not join/exactly match Carnegie names
joined_na_inst <- inst_join %>% 
  filter(is.na(NAME)) %>% 
  select(inst_name) %>% distinct()

#identify respondent inst that DID join/exactly match Carnegie names
joined_matches <- inst_join %>% 
  filter(inst_name == NAME) %>% 
  distinct()

#fuzzy join----
missing_fuzzy_join <- joined_na_inst %>%
  mutate(inst_name = map(inst_name, replace_uny),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_inst_abbrv),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_inst_name),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_campus),
         inst_name = unlist(inst_name),
         inst_name = map(inst_name, fix_inst_name),
         inst_name = unlist(inst_name),
         inst_name = str_squish(inst_name),
         ) %>% #another attempt to repair names
  stringdist_left_join(., carnegie_inst_names, 
                       by = c("inst_name" = "NAME"), 
                       method = "lcs", max_dist = 6
  ) %>% #use fuzzy join to catch potential mis-spellings, campuses, etc.
  distinct()

#list of correct matches from fuzzy join
slice_list <- c(1, 4, 5, 7, 8, 27, 42:45, 63, 65, 75, 78, 80,
                88, 101, 126, 133, 199, 200, 204, 220, 227, 
                232:234, 236, 259, 260, 276:278, 300:304, 309,
                310, 325, 326, 341, 343, 353:355, 357, 362, 
                380, 381, 385:387, 389, 390, 392:396, 407,
                423, 425:427, 430, 440, 444) 

fuzzy_matches <- missing_fuzzy_join %>% 
  filter(!is.na(NAME)) %>% 
  #filter(inst_name != NAME) %>% 
  slice(slice_list)

#final lists----
all_matches <- rbind(joined_matches, fuzzy_matches)

final_missing <- anti_join(missing_fuzzy_join, 
                           fuzzy_matches, by = "inst_name") %>% 
  #filter(!is.na(NAME)) %>% 
  #filter(inst_name != NAME) %>% 
  #slice(-slice_list) %>% 
  select(inst_name) %>% distinct() %>% 
  anti_join(., all_matches, by = "inst_name")

#save csv files----
write_csv(final_missing, 
          paste0("output/missing_inst_", Sys.Date(), ".csv"))

write_csv(all_matches, 
          paste0("output/carnegie_inst_matches_", Sys.Date(), ".csv"))

write_csv(clean_surv_inst, 
          paste0("output/cleaned_survey_inst_", Sys.Date(), ".csv"))
